---
- name: Install Sealed Secrets via Kustomize
  vars:
    # gh api repos/bitnami-labs/sealed-secrets/releases/latest --jq '.tag_name'
    sealed_secrets_version: "v0.36.1"
    temp_dir: "/tmp/sealed-secrets-install"
  block:
    - name: Debug host information
      debug:
        msg:
          - "Target Host (inventory_hostname): {{ inventory_hostname }}"
          - "Actual execution (ansible_host): {{ ansible_host | default(inventory_hostname) }}"

    # 1. Verzeichnis vorbereiten
    - name: Ensure temporary directory exists
      file:
        path: "{{ temp_dir }}"
        state: directory
        mode: '0777'

    # 2. Das kustomization.yaml schreiben
    # Hier definieren wir die Remote-URL und patchen direkt Einstellungen
    - name: Create kustomization.yaml
      copy:
        dest: "{{ temp_dir }}/kustomization.yaml"
        content: |
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          
          resources:
            - https://github.com/bitnami-labs/sealed-secrets/releases/download/{{ sealed_secrets_version }}/controller.yaml
          
          # Optional: Patches, um Standardwerte zu ändern (hier: Rotation deaktivieren)
          patches:
            - target:
                kind: Deployment
                name: sealed-secrets-controller
                namespace: kube-system
              patch: |-
                - op: add
                  path: /spec/template/spec/containers/0/command/-
                  value: "--key-renew-period=0"
                - op: add
                  path: /spec/template/spec/containers/0/resources
                  value:
                    requests:
                      cpu: "10m"
                      memory: "32Mi"
                    limits:
                      cpu: "200m"
                      memory: "128Mi"
                - op: add
                  path: /metadata/annotations/keel.sh~1policy
                  value: "patch"
                - op: add
                  path: /metadata/annotations/keel.sh~1match-tag
                  value: "true"
                - op: add
                  path: /metadata/annotations/keel.sh~1pollSchedule
                  value: "@every 24h"
                - op: add
                  path: /metadata/annotations/keel.sh~1trigger
                  value: "poll"
                - op: add
                  path: /spec/template/spec/nodeSelector
                  value:
                    kubernetes.io/arch: amd64

    # 3. Kustomize Build ausführen und auf Cluster anwenden
    # Der 'lookup' führt lokal 'kustomize build' aus und übergibt das Ergebnis an das K8s-Modul
    - name: Apply Kustomize build to Cluster
      kubernetes.core.k8s:
        definition: "{{ lookup('kubernetes.core.kustomize', dir=temp_dir) }}"
        state: present
  always:
    # 4. Aufräumen (Optional)
    - name: Cleanup temporary directory
      file:
        path: "{{ temp_dir }}"
        state: absent
  # delegate_to: localhost