---
# Dummy values — overridden by vault.yml

ansible_host: "192.168.124.100"
host_octet: 100
mailname: "k3smaster.example.com"
ovs_bridge_name: "br0"
default_route_iface: "br0.124"
clevis_luks_passphrase: "changeme"
k3s_node_ip: "192.168.124.100"
# Flannel VTEP must use the K3s cluster VLAN interface, not the default route interface
k3s_flannel_iface: "br0.124"
ovs_vlan_extra:
  124:
    extra_routes:
      - to: default
        via: 192.168.124.1
        table: 124
      - to: 192.168.122.0/24
        via: 192.168.124.1
        table: 124
fwmark_routing:
  - iface: "br0.124"
    mark: "0x65"
    inbound_src: "192.168.122.0/24"
    inbound_dst: "192.168.124.100"
    table: 124
