module(load="omjournal")

# Remote Nachrichten (nicht von localhost) an Journal weiterleiten
# Fluent-bit prepends hostname to message for journal compatibility
# Use stop to prevent duplicate writes to /var/log/syslog
if $fromhost-ip != "127.0.0.1" then {
  action(type="omjournal")
  stop
}