---
# HelmChartConfig for K3s metrics-server
# https://github.com/kubernetes-sigs/metrics-server/tree/master/charts/metrics-server
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  valuesContent: |-
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 256Mi