---
# defaults file for k3sserver
# ~ $ curl -s https://api.github.com/repos/k3s-io/k3s/releases | jq -r '.[0].tag_name'
# v1.35.4+k3s1

k3s_version: "v1.35.4+k3s1"
k3s_node_ip: "{{ ansible_facts.default_ipv4.address }}"

kubeconfig_context_name: "admin@cluster"

# Kubelet image garbage collection
kubelet_image_gc_high_threshold: 95
kubelet_image_gc_low_threshold: 90
kubelet_image_minimum_gc_age: "24h"

# HAProxy stats password (overridden by vault)
haproxy_stats_password: "changeme"